<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Normalizer;

use MagedIn\Formatter\OnlyNumber;
use MagedIn\Formatter\StringSize;

class Cpf
{
    /**
     * @var int
     */
    const MAX_LENGTH = 11;

    /**
     * @var string
     */
    const PAD_STRING = '0';

    /**
     * @var OnlyNumber
     */
    private $onlyNumber;

    /**
     * @var StringSize
     */
    private $stringSize;

    public function __construct(
        OnlyNumber $onlyNumber,
        StringSize $stringSize
    ) {
        $this->onlyNumber = $onlyNumber;
        $this->stringSize = $stringSize;
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function normalize(string $value): string
    {
        $value = $this->onlyNumber->format($value);
        $value = $this->stringSize->format($value, self::MAX_LENGTH, self::PAD_STRING, STR_PAD_LEFT);
        return $value;
    }
}
