<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Normalizer;

use MagedIn\Formatter\OnlyNumber;
use MagedIn\Formatter\StringSize;

class Postcode
{
    /**
     * @var int
     */
    const MAX_LENGTH = 8;

    /**
     * @var OnlyNumber
     */
    private $onlyNumber;

    /**
     * @var StringSize
     */
    private $stringSize;

    public function __construct(
        OnlyNumber $onlyNumber,
        StringSize $stringSize
    ) {
        $this->onlyNumber = $onlyNumber;
        $this->stringSize = $stringSize;
    }

    /**
     * @param string $postcode
     *
     * @return string
     */
    public function normalize(string $postcode): string
    {
        $postcode = $this->onlyNumber->format($postcode);
        $postcode = $this->stringSize->format($postcode, self::MAX_LENGTH, '0', STR_PAD_LEFT);
        $postcode = substr($postcode, -self::MAX_LENGTH, self::MAX_LENGTH);
        return (string) $postcode;
    }
}
