<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\DateTime;

use DateTime;

class AbstractDateTime
{
    /**
     * @var string
     */
    const DEFAULT_FORMAT = 'Y-m-d H:i:s';

    /**
     * @param null|string|int|DateTime $datetime
     *
     * @return int|null
     */
    protected function getDatetime($datetime = null): ?int
    {
        if (null === $datetime) {
            return self::getCurrentTimestamp();
        }

        if ($datetime instanceof DateTime) {
            $datetime = (string) $datetime->format(self::DEFAULT_FORMAT);
        }

        if (is_string($datetime)) {
            $datetime = strtotime($datetime);
        }

        return $datetime;
    }

    /**
     * @return int
     */
    protected function getCurrentTimestamp(): int
    {
        return time();
    }
}
