<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\DateTime;

use DateTime;

class Year extends AbstractDateTime
{
    /**
     * When a full year has 366 days.
     *
     * @param null|string|int|DateTime $datetime
     *
     * @return bool
     */
    public function isLeapYear($datetime = null): bool
    {
        $year = (int) date('Y', self::getDatetime($datetime));
        return self::checkLeapYear($year);
    }

    /**
     * @param int $year
     *
     * @return bool
     */
    private function checkLeapYear(int $year): bool
    {
        /**
         * Another way of calculate this.
         *
         * $february = mktime(0, 0, 0, 2, 1, $year);
         * $daysCount = date('t', $february);
         *
         * return ($daysCount == 29);
         */

        /**
         * First check if the year is divisible by 4 and not by 100.
         */
        if (($year % 4 == 0) && ($year % 100 != 0)) {
            return true;
        }

        /**
         * Or if the year is divisible by 400.
         */
        if ($year % 400 == 0) {
            return true;
        }

        return false;
    }
}
