<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Block\Form\Element;

use MagedIn\Framework\Magento2\Module\Metadata as ModuleMetadata;
use Magento\Framework\Data\Form\Element\CollectionFactory;
use Magento\Framework\Data\Form\Element\Factory;
use Magento\Framework\Data\Form\Element\Label;
use Magento\Framework\Escaper;

/**
 * Class Label
 * A customized label for using in admin form.
 */
class VersionLabel extends Label
{
    /**
     * @var ModuleMetadata
     */
    private ModuleMetadata $moduleMetadata;

    /**
     * @var string|null
     */
    private ?string $packageName;

    /**
     * @param ModuleMetadata $moduleMetadata
     * @param Factory $factoryElement
     * @param CollectionFactory $factoryCollection
     * @param Escaper $escaper
     * @param string|null $packageName
     * @param array $data
     */
    public function __construct(
        ModuleMetadata $moduleMetadata,
        Factory $factoryElement,
        CollectionFactory $factoryCollection,
        Escaper $escaper,
        string $packageName = null,
        $data = []
    ) {
        $this->moduleMetadata = $moduleMetadata;
        $this->packageName = $packageName;
        parent::__construct($factoryElement, $factoryCollection, $escaper, $data);
    }

    /**
     * Get module's version. First try to get it from composer installation otherwise use the config information.
     *
     * @return string
     */
    public function getValue(): string
    {
        if (empty($this->packageName)) {
            return (string) $this->getData('version');
        }
        return $this->moduleMetadata->getVersion($this->packageName);
    }

    /**
     * DocBlock for method.
     *
     * @return string
     */
    public function getElementHtml(): string
    {
        $html = parent::getElementHtml();
        $note = __('This is the current version of your module installation.');
        $html .= '<p class="note"><span>' . $note . '</span></p>';
        return $html;
    }
}
