<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Formatter;

class OnlyNumber
{
    /**
     * @param string $value
     *
     * @return string
     */
    public function format(string $value): string
    {
        return preg_replace('/[^0-9]/is', null, $value);
    }
}
