<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Formatter;

class StringSize
{
    /**
     * @param string $value
     * @param int    $length
     * @param string $string
     * @param int    $type
     *
     * @return string
     */
    public function format(string $value, int $length, string $string, int $type = STR_PAD_RIGHT): string
    {
        return str_pad($value, $length, $string, $type);
    }
}
