<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\DataObject;

use Magento\Framework\DataObject;

/**
 * Class Copy
 * Provides functionality to copy specified fields from one DataObject to another.
 */
class Copy
{
    /**
     * Copies specified fields from the source DataObject to the target DataObject.
     *
     * @param DataObject $source The source object containing the data to copy.
     * @param DataObject $target The target object where the data will be copied to.
     * @param array $fields An array of field names to copy from the source to the target.
     * @return void
     */
    public function copy(DataObject $source, DataObject $target, array $fields): void
    {
        /**
         * Copies a single field's value from one DataObject to another.
         *
         * @param string $field The name of the field to copy.
         * @param DataObject $source The source object containing the field's value.
         * @param DataObject $target The target object where the field's value will be set.
         */
        $copier = function (string $field, DataObject $source, DataObject $target) {
            $target->setData($field, $source->getData($field));
        };

        // Iterate over the fields and copy each one using the copier function.
        array_map(function (string $field) use ($copier, $source, $target) {
            $copier($field, $source, $target);
        }, $fields);
    }
}
