<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Helper;

class StringHelper
{
    /**
     * @param string $text
     * @return string
     */
    public function toCamelCase(string $text): string
    {
        $text = $this->upperCaseWords($text);
        $text = str_replace(' ', '', $text);
        return $this->lowerCaseFirst($text);
    }

    /**
     * @param string $text
     * @return string
     */
    public function toLowerCase(string $text): string
    {
        return strtolower($text);
    }

    /**
     * @param string $text
     * @return string
     */
    public function toUpperCase(string $text): string
    {
        return strtoupper($text);
    }

    /**
     * @param string $text
     * @return string
     */
    public function lowerCaseFirst(string $text): string
    {
        return lcfirst($text);
    }

    /**
     * @param string $text
     * @return string
     */
    public function upperCaseFirst(string $text): string
    {
        return ucfirst($text);
    }

    /**
     * @param string $text
     * @param string $separators
     * @return string
     */
    public function upperCaseWords(string $text, string $separators = " \t\r\n\f\v"): string
    {
        return ucwords($text, $separators);
    }
}
