<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\View\Element\UiComponent\Control\Button;

/**
 * Class BackButton
 *
 * Represents a "Back" button in the UI component for the rule edit page.
 * Provides functionality to generate button data and determine the back URL.
 */
class BackButton extends AbstractButton
{
    /**
     * Get button data
     *
     * This method returns an array containing the configuration for the "Back" button,
     * including its label, click action, CSS class, and sort order.
     *
     * @return array The button configuration data.
     */
    public function getButtonData(): array
    {
        return [
            'label' => __($this->getLabel() ?? 'Back'),
            'on_click' => sprintf("location.href = '%s';", $this->getBackUrl()),
            'class' => $this->getClass() ?? 'back',
            'sort_order' => $this->getSortOrder() ?? 10,
        ];
    }

    /**
     * Get URL for back button
     *
     * This method generates the URL that the "Back" button will redirect to when clicked.
     *
     * @return string The URL for the "Back" button.
     */
    protected function getBackUrl(): string
    {
        return $this->getUrl('*/*/');
    }
}
