<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\View\Element\UiComponent\Control\Button;

/**
 * Save button for edit page
 */
class SaveButton extends AbstractButton
{
    /**
     * Retrieve the data for the save button.
     *
     * @return array The button configuration data.
     */
    public function getButtonData(): array
    {
        return [
            'label' => __($this->getLabel() ?? 'Save'),
            'class' => $this->getClass() ?? 'save primary',
            'data_attribute' => [
                'mage-init' => [
                    'buttonAdapter' => [
                        'actions' => [
                            [
                                'targetName' => $this->getTargetName(),
                                'actionName' => $this->getActionName(),
                                'params' => $this->getParams(),
                            ]
                        ]
                    ]
                ]
            ],
            'sort_order' => $this->getSortOrder() ?? 100,
        ];
    }

    /**
     * Retrieve the target name for the button action.
     *
     * @return string The target name.
     */
    protected function getTargetName(): string
    {
        return '';
    }

    /**
     * Retrieve the action name for the button.
     *
     * @return string|null The action name, or null if not set.
     */
    protected function getActionName(): ?string
    {
        return 'save';
    }

    /**
     * Retrieve the parameters for the button action.
     *
     * @return array The action parameters.
     */
    protected function getParams(): array
    {
        return [
            false
        ];
    }
}
