<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Framework\Magento2\Model\Locator;

/**
 * Interface for a locator system that provides methods for retrieving locators,
 * resolving IDs, and creating new instances.
 */
interface LocatorInterface
{
    /**
     * Get the locator.
     *
     * @param int|null $id
     *
     * @return mixed
     */
    public function get(?int $id = null);

    /**
     * Get the locator ID.
     *
     * @param int|null $id
     *
     * @return int|null
     */
    public function resolveId(int $id = null): ?int;

    /**
     * Create new instance.
     *
     * @param array $data
     *
     * @return mixed
     */
    public function createNewInstance(array $data = []);
}
