<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field\MetaConfigGenerator;

use MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field\MetaConfigGeneratorInterface;

/**
 * DocBlock for AbstractGenerator class.
 */
abstract class AbstractGenerator implements MetaConfigGeneratorInterface
{
}
