<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field\MetaConfigGenerator;

use MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field\MetaConfigGeneratorInterface;

/**
 * DocBlock for Base class.
 */
class Field implements MetaConfigGeneratorInterface
{
    /**
     * DocBlock for method.
     *
     * @param array $config
     *
     * @return array
     */
    public function generate(array $config): array
    {
        $baseConfig = [
            'componentType' => 'field',
            'dataType' => 'text',
            'label' => '',
            'sortOrder' => 10,
            'notice' => null,
            'visible' => true,
            'disabled' => false,
        ];
        return array_merge($baseConfig, $config);
    }
}
