<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field\MetaConfigGenerator;

/**
 * DocBlock for Input class.
 */
class InsertListing extends Field
{
    /**
     * @inheirtDoc
     */
    public function generate(array $config): array
    {
        $baseConfig = [
            'componentType' => 'insertListing',
            'autoRender' => true,
            'render_url' => null,
            'update_url' => null,
            'realTimeLink' => false,
            'dataLinks' => [
                'imports' => false,
                'exports' => false,
            ],
            'component' => 'Magento_Ui/js/form/components/insert-listing',
            'ns' => null,
            'externalProvider' => null,
            'selectionsProvider' => null,
            'externalFilterMode' => true,
            'exports' => [],
            'destinationIdsFieldSelector' => null,
        ];
        return array_merge(parent::generate($baseConfig), $config);
    }
}
