<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field;

use Magento\Framework\Exception\InvalidArgumentException;

/**
 * DocBlock for ConfigGenerator class.
 */
class MataConfigGenerator
{
    /**
     * @var MetaConfigGeneratorFactory
     */
    private MetaConfigGeneratorFactory $generatorFactory;

    public function __construct(
        MetaConfigGeneratorFactory $generatorFactory
    ) {
        $this->generatorFactory = $generatorFactory;
    }

    /**
     * Generates the meta configuration for a field.
     *
     * @param array $config The configuration array for the field.
     * @param string $type
     *
     * @return array The generated meta configuration.
     * @throws InvalidArgumentException
     */
    public function generate(string $type, array $config): array
    {
        $generator = $this->generatorFactory->create($type);
        return $generator->generate($config);
    }
}
