<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\Framework\Magento2\Ui\DataProvider\Modifier\Field;

/**
 * DocBlock for MetaConfigGeneratorInterface interface.
 */
interface MetaConfigGeneratorInterface
{
    /**
     * Generates the meta configuration for a field.
     *
     * @param array $config The configuration array for the field.
     *
     * @return array The generated meta configuration.
     */
    public function generate(array $config): array;
}
