<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Module\Integration\System\Adminhtml\Source;

use Magento\Framework\Data\OptionSourceInterface;

abstract class AbstractSource implements OptionSourceInterface
{
    /**
     * @var array
     */
    private $options = [];

    /**
     * @return array
     */
    public function toOptionArray(): array
    {
        if (!$this->options) {
            foreach ($this->toOption() as $value) {
                $this->options[] = [
                    'value' => $value,
                    'label' => __($this->getOptionLabel($value)),
                ];
            }
        }
        return $this->options;
    }

    /**
     * @return array
     */
    abstract public function getOptions(): array;

    /**
     * @param string $value
     *
     * @return string
     */
    abstract public function getOptionLabel(string $value): ?string;
}
