<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Magento2\Framework\Module\Integration\System\Adminhtml\Source;

class Environment extends AbstractSource
{
    /**
     * @const string
     */
    public const ENVIRONMENT_PRODUCTION = 'production';

    /**
     * @const string
     */
    public const ENVIRONMENT_TESTING = 'testing';

    /**
     * @const string
     */
    public const ENVIRONMENT_TEST = 'test';

    /**
     * @const string
     */
    public const ENVIRONMENT_STAGING = 'staging';

    /**
     * @const string
     */
    public const ENVIRONMENT_SANDBOX = 'sandbox';

    /**
     * @const string
     */
    public const ENVIRONMENT_DEVELOPMENT = 'development';

    /**
     * @var string[]
     */
    private $allowedOptions = [
        self::ENVIRONMENT_PRODUCTION,
        self::ENVIRONMENT_STAGING,
        self::ENVIRONMENT_TESTING,
        self::ENVIRONMENT_TEST,
        self::ENVIRONMENT_SANDBOX,
        self::ENVIRONMENT_DEVELOPMENT,
    ];

    /**
     * @var string[]
     */
    protected $optionLabels = [
        self::ENVIRONMENT_PRODUCTION  => 'Production',
        self::ENVIRONMENT_STAGING     => 'Staging',
        self::ENVIRONMENT_TESTING     => 'Testing',
        self::ENVIRONMENT_TEST        => 'Test',
        self::ENVIRONMENT_SANDBOX     => 'Sandbox',
        self::ENVIRONMENT_DEVELOPMENT => 'Development',
    ];

    /**
     * @var string[]
     */
    protected $defaultOptions = [
        self::ENVIRONMENT_PRODUCTION,
        self::ENVIRONMENT_STAGING,
        self::ENVIRONMENT_TESTING,
        self::ENVIRONMENT_TEST,
        self::ENVIRONMENT_SANDBOX,
        self::ENVIRONMENT_DEVELOPMENT,
    ];

    /**
     * @return array
     */
    public function getOptions(): array
    {
        return $this->defaultOptions;
    }

    /**
     * @param string $value
     *
     * @return string|null
     */
    public function getOptionLabel(string $value): ?string
    {
        return $this->optionLabels[$value] ?? null;
    }
}
