<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Module;

use Magento\Framework\Module\ModuleListInterface;

class ModuleMetadataProvider
{
    /**
     * @var ModuleListInterface
     */
    private ModuleListInterface $moduleList;

    public function __construct(
        ModuleListInterface $moduleList
    ) {
        $this->moduleList = $moduleList;
    }

    /**
     * @param string $moduleName
     *
     * @return string|null
     */
    public function getVersion(string $moduleName): ?string
    {
        $metadata = $this->moduleList->getOne($moduleName);
        return $metadata['setup_version'] ?? null;
    }

    /**
     * @param string $moduleName
     *
     * @return string|null
     */
    public function getQualifiedVersion(string $moduleName): ?string
    {
        $version = $this->getVersion($moduleName);
        if (!$version) {
            return (string) __('Undefined Module Version');
        }
        return "v{$version}";
    }

    /**
     * @param string $moduleName
     *
     * @return string
     */
    public function getVersionName(string $moduleName): string
    {
        return vsprintf("%s - %s", [
            $moduleName,
            $this->getQualifiedVersion($moduleName)
        ]);
    }
}
