<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\Component\Config\Generator\Form\Field;

/**
 * Checkbox field configuration generator
 */
class Checkbox extends AbstractField
{
    /**
     * @var string
     */
    protected string $formElement = 'checkbox';

    /**
     * @var string
     */
    protected string $dataType = 'boolean';

    /**
     * @var array
     */
    protected array $valueMap = [
        'true' => '1',
        'false' => '0',
    ];

    /**
     * Set value map for checkbox
     *
     * @param string $trueValue Value for checked state
     * @param string $falseValue Value for unchecked state
     * @return $this
     */
    public function setValueMap(string $trueValue, string $falseValue): self
    {
        $this->valueMap = [
            'true' => $trueValue,
            'false' => $falseValue,
        ];
        return $this;
    }

    /**
     * Customize configuration array with checkbox-specific settings
     *
     * @param array $config Base configuration array
     * @return array Modified configuration array
     */
    protected function customizeConfig(array $config): array
    {
        $config['arguments']['data']['config']['valueMap'] = $this->valueMap;
        return $config;
    }
}
