<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\Component\Config\Generator\Form\Field;

/**
 * Date field configuration generator
 */
class Date extends AbstractField
{
    /**
     * @var string
     */
    protected string $formElement = 'date';

    /**
     * @var string
     */
    protected string $dataType = 'date';

    /**
     * @var string
     */
    private string $dateFormat = 'MM/dd/yyyy';

    /**
     * @var bool
     */
    private bool $showTime = false;

    /**
     * @param string $dateFormat Date format
     * @param bool $showTime Whether to include time picker
     */
    public function __construct(string $dateFormat = 'MM/dd/yyyy', bool $showTime = false)
    {
        $this->dateFormat = $dateFormat;
        $this->showTime = $showTime;
    }

    /**
     * Set date format
     *
     * @param string $dateFormat
     * @return $this
     */
    public function setDateFormat(string $dateFormat): self
    {
        $this->dateFormat = $dateFormat;
        return $this;
    }

    /**
     * Set whether to show time
     *
     * @param bool $showTime
     * @return $this
     */
    public function setShowTime(bool $showTime): self
    {
        $this->showTime = $showTime;
        return $this;
    }

    /**
     * Customize configuration array with date-specific settings
     *
     * @param array $config Base configuration array
     * @return array Modified configuration array
     */
    protected function customizeConfig(array $config): array
    {
        $config['arguments']['data']['config']['dateFormat'] = $this->dateFormat;

        if ($this->showTime) {
            $config['arguments']['data']['config']['showTime'] = true;
            $config['arguments']['data']['config']['timeFormat'] = 'HH:mm:ss';
        }

        $config['arguments']['data']['config']['pickerDefaultDateFormat'] = 'MM/dd/yyyy';
        $config['arguments']['data']['config']['pickerDefaultTimeFormat'] = 'HH:mm:ss';

        return $config;
    }
}
