<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\Component\Config\Generator\Form\Field;

/**
 * Number field configuration generator
 */
class Number extends AbstractField
{
    /**
     * @var string
     */
    protected string $formElement = 'input';

    /**
     * @var string
     */
    protected string $dataType = 'number';

    /**
     * @var int|null
     */
    private ?int $min = null;

    /**
     * @var int|null
     */
    private ?int $max = null;

    /**
     * @param int|null $min Minimum value
     * @param int|null $max Maximum value
     */
    public function __construct(?int $min = null, ?int $max = null)
    {
        $this->min = $min;
        $this->max = $max;
    }

    /**
     * Set minimum value
     *
     * @param int|null $min
     * @return $this
     */
    public function setMin(?int $min): self
    {
        $this->min = $min;
        return $this;
    }

    /**
     * Set maximum value
     *
     * @param int|null $max
     * @return $this
     */
    public function setMax(?int $max): self
    {
        $this->max = $max;
        return $this;
    }

    /**
     * Customize configuration array with number-specific settings
     *
     * @param array $config Base configuration array
     * @return array Modified configuration array
     */
    protected function customizeConfig(array $config): array
    {
        if ($this->min !== null) {
            $config['arguments']['data']['config']['validation'] = $config['arguments']['data']['config']['validation'] ?? [];
            $config['arguments']['data']['config']['validation']['min_text_length'] = $this->min;
        }

        if ($this->max !== null) {
            $config['arguments']['data']['config']['validation'] = $config['arguments']['data']['config']['validation'] ?? [];
            $config['arguments']['data']['config']['validation']['max_text_length'] = $this->max;
        }

        return $config;
    }
}
