<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\Component\Config\Generator\Form\Field;

/**
 * Select field configuration generator
 */
class Select extends AbstractField
{
    /**
     * @var string
     */
    protected string $formElement = 'select';

    /**
     * @var string
     */
    protected string $dataType = 'select';

    /**
     * @var array
     */
    private array $options = [];

    /**
     * @var bool
     */
    private bool $multiple = false;

    /**
     * @param array $options Select options
     * @param bool $multiple Whether multiple selection is allowed
     */
    public function __construct(array $options = [], bool $multiple = false)
    {
        $this->options = $options;
        $this->multiple = $multiple;
    }

    /**
     * Set select options
     *
     * @param array $options
     * @return $this
     */
    public function setOptions(array $options): self
    {
        $this->options = $options;
        return $this;
    }

    /**
     * Set whether multiple selection is allowed
     *
     * @param bool $multiple
     * @return $this
     */
    public function setMultiple(bool $multiple): self
    {
        $this->multiple = $multiple;
        return $this;
    }

    /**
     * Customize configuration array with select-specific settings
     *
     * @param array $config Base configuration array
     * @return array Modified configuration array
     */
    protected function customizeConfig(array $config): array
    {
        $config['arguments']['data']['config']['options'] = $this->options;

        if ($this->multiple) {
            $config['arguments']['data']['config']['multiple'] = true;
            $config['arguments']['data']['config']['size'] = count($this->options) > 10 ? 10 : count($this->options);
        }

        return $config;
    }
}
