<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\Framework\Magento2\Ui\Component\Config\Generator\Form\Field;

/**
 * WYSIWYG editor field configuration generator
 */
class Wysiwyg extends Textarea
{
    /**
     * @var bool
     */
    private bool $wysiwygConfigurable = true;

    /**
     * @var array
     */
    private array $additionalConfig = [];

    /**
     * @param bool $wysiwygConfigurable Whether WYSIWYG is configurable
     * @param array $additionalConfig Additional WYSIWYG config
     */
    public function __construct(bool $wysiwygConfigurable = true, array $additionalConfig = [])
    {
        $this->wysiwygConfigurable = $wysiwygConfigurable;
        $this->additionalConfig = $additionalConfig;
    }

    /**
     * Set whether WYSIWYG is configurable
     *
     * @param bool $wysiwygConfigurable
     * @return $this
     */
    public function setWysiwygConfigurable(bool $wysiwygConfigurable): self
    {
        $this->wysiwygConfigurable = $wysiwygConfigurable;
        return $this;
    }

    /**
     * Set additional WYSIWYG config
     *
     * @param array $additionalConfig
     * @return $this
     */
    public function setAdditionalConfig(array $additionalConfig): self
    {
        $this->additionalConfig = $additionalConfig;
        return $this;
    }

    /**
     * Customize configuration array with WYSIWYG-specific settings
     *
     * @param array $config Base configuration array
     * @return array Modified configuration array
     */
    protected function customizeConfig(array $config): array
    {
        $config = parent::customizeConfig($config);

        $config['arguments']['data']['config']['template'] = 'ui/form/field';
        $config['arguments']['data']['config']['wysiwyg'] = true;
        $config['arguments']['data']['config']['wysiwygConfigData'] = [
            'add_variables' => true,
            'add_widgets' => true,
            'add_images' => true,
            'add_directives' => true
        ];

        if ($this->wysiwygConfigurable) {
            $config['arguments']['data']['config']['wysiwygConfigurable'] = true;
        }

        if (!empty($this->additionalConfig)) {
            $config['arguments']['data']['config']['wysiwygConfigData'] = array_merge(
                $config['arguments']['data']['config']['wysiwygConfigData'],
                $this->additionalConfig
            );
        }

        return $config;
    }
}
